### ISSUE TITLE
iron-list with grid-view

### ISSUE THREAD

**Issue by julianmanandhar** [Shuvayatra/shuvayatra-pwa#18]
@tyohan 
We are using iron-list with iron-scroll-threshold to lazy load the paginated posts. 

However when we try grid view with iron-list, only first 3-4 elements are rendered and remaining only gets rendered when we resize the browser window.

Could you please look into the issue. Thanks.

**Comment by tyohan** [comment]
@julianraj the problem with the iron-list is you need to have fixed height on each list item. If not, it will not work well. So if we can't use fixed height isn't possible then try to use this approach https://www.polymer-project.org/1.0/docs/devguide/templates#large-list-perf
